language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"

script: npm run-script coveralls
    
after_success:
        - ./node_modules/.bin/jscoverage lib lib-cov
        - ./node_modules/.bin/mocha YOUR_TESTS/**.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
